Update xinit and zshrc

diff --git a/meta/configs/zshrc b/meta/configs/zshrc
--- a/meta/configs/zshrc
+++ b/meta/configs/zshrc
@@ -92,12 +92,28 @@ fi
 
 # start x as default
 if [[ $(uname -s) == "Linux" ]] && [[ -z "$DISPLAY" ]] && [[ $(tty) = /dev/tty1 ]]; then
-   startx
-   #  XDG_SESSION_TYPE=wayland dbus-run-session gnome-session
+   dialog --yesno '    Run on Wayland? \n    (X.org Fallback)' 0 0
+   if [ $? = 0 ]; then
+       XDG_SESSION_TYPE=wayland dbus-run-session startplasma-wayland
+   else
+       startx
+   fi
    exit
 fi
 
 if [ -x "$(command -v exa)" ]; then
     alias ls='exa -l'
 fi
+
+
+function run_main {
+  if [[ -e "main.c" ]]; then
+    gcc -o main main.c && ./main
+  elif [[ -e "main.cpp" ]]; then
+    g++ -o main main.cpp && ./main
+  else
+    echo "Error: No valid file found."
+  fi
+}
+
 
